### ISSUE TITLE
[BUG] Syncplicity and SAP lama have invalid package names

### ISSUE THREAD

**Issue by wickedest** [Axway-API-Builder-Ext/api-builder-extras#15]
**Artefact version you are using**
latest

**API-Builder version you are using**
latest

**Actual behavior**
Installing either "AWS-Lambda" or "Syncplicity" in API Builder Plugins UI will fail with invalid package names (404).  The issue is that their package names differ from the convention used with in Axway-API-Builder-Ext.  As a result, they were added to API Builder with incorrect package names (arguably our fault).  However, it appears that the intention was that these be named the same as their folders in this repo:

* https://github.com/Axway-API-Builder-Ext/api-builder-extras/blob/master/api-builder-plugin-fc-syncplicity/package.json
* https://github.com/Axway-API-Builder-Ext/api-builder-extras/blob/master/api-builder-plugin-fc-sap-lama/package.json

**Expected behavior**
The plugins install correctly.

**Log-Output in Debug**

**Comment by cwiechmann** [comment]
Hi @wickedest, would the following package names be okay?

`@axway-api-builder-ext/api-builder-plugin-fc-syncplicity`
`@axway-api-builder-ext/api-builder-plugin-fc-sap-lama`

I would like to have it synchronized with the repository folder.

**Comment by wickedest** [comment]
yes, correct

**Comment by cwiechmann** [comment]
Package names fixed and new modules released.
