### ISSUE TITLE
Ability to read/write files 

### ISSUE THREAD

**Issue by arunkumard** [Axway-API-Builder-Ext/api-builder-extras#25]
**User story**
A Credit union collects personal information during account opening…
They collect things like ID images from the customers for the Proof of identity. 
They collect all of it and store it with their sales platform  on the cloud .

Their Requirement is to build an API that the cloud based sales platform will call to move theese images from their cloud  to the Credit Union's On-Prem shared folder .

They want an API that Axway will provide where they can POST the content  
(Base64 encoded) in the BODY .

The API with Axway will then read the BODY, Base64 decode it (maybe serialize it)  ,  and then save the content to a shared folder.

**Additional context**

Size of the files would be very small in KBs.

**Comment by cwiechmann** [comment]
@arunkumard, the File-Flow node 0.0.3 can now write files. Please check here: 
https://github.com/Axway-API-Builder-Ext/api-builder-extras/tree/master/api-builder-plugin-fn-file

It would be good if you can test it and provide feedback.
