### ISSUE TITLE
[BUG] 2.0.0 ForEach does not work

### ISSUE THREAD

**Issue by wickedest** [Axway-API-Builder-Ext/api-builder-extras#65]
**Artefact version you are using**
2.0.0

**API-Builder version you are using**
Latest

**Actual behavior**
```js
{"message":"Cannot read property 'getFlow' of null"}
```

**Expected behavior**
The ForEach should execute a flow.

**Log-Output in Debug**

**Comment by cwiechmann** [comment]
I have deprecated the Foreach-Plugin in favor of the official plugin: @axway/api-builder-plugin-invoke-flow. Closing this issue now.
