### ISSUE TITLE
[BUG] 2.0.0 ForEach deletes flows on uninstall

### ISSUE THREAD

**Issue by wickedest** [Axway-API-Builder-Ext/api-builder-extras#66]
**Artefact version you are using**
ForEach 2.0.0

**API-Builder version you are using**
Latest

**Actual behavior**
1. `npm install @axway-api-builder-ext/api-builder-plugin-fn-foreach`
1. Try to use it, and find out it does not work.  Modify one or both example flows.
1. `npm install @axway-api-builder-ext/api-builder-plugin-fn-foreach@1.0.0`
1. `ls flows`

The example flows are deleted.

Note that there is a related issue where just using 2.0.0, wiping node_modules and re-installing will re-install the examples, wiping any changes made to those files.

**Expected behavior**

Flows should not be deleted.  It's arguable whether or not they should be deleted.  Are they backwardly compatible?  At the very least, if they're not the user will get an error that they are not.  However, deleting them has potential to delete someone's work.

Also, I haven't verified this, but it is also possible a 2.0.1 patch might uninstall 2.0.0 and remove the example flows.  Maybe.

**Log-Output in Debug**

**Comment by cwiechmann** [comment]
I have deprecated the Foreach-Plugin in favor of the official plugin: @axway/api-builder-plugin-invoke-flow. Closing this issue now.
