### ISSUE TITLE
[BUG] Postgres-Connector crashes API-Builder when running on NodeJS >14

### ISSUE THREAD

**Issue by jmcabrera** [Axway-API-Builder-Ext/api-builder-extras#71]
**Artefact version you are using**
connector/postgres@1.0.3

**API-Builder version you are using**
4.69.0

**Actual behavior**
With node 14, Starting the postgresql connector stops the builder abruptly (see logs below)
With node 12, starts normally.

**Expected behavior**
The latest version of this plugin should start normally with the latest version of NodeJS
It might just be a needed bump in pg version: version 7.x does not work on node 14, and pg 8.x requires it.
As I understood it, it boils down to a breaking change on how NodeJS implements streams...

**Log-Output in Debug**

    [prompt> npm start
    
    > uc3@1.0.0 start
    > node .
    
    1633605861720 DEBUG configuration applied in this order: /Users/jcabrera/work/clients/Imerys/uc3/apibuilder/conf/api.default.js,/Users/jcabrera/work/clients/Imerys/uc3/apibuilder/conf/default.js,/Users/jcabrera/work/clients/Imerys/uc3/apibuilder/conf/postgres.default.js
    1633605861721 DEBUG The maximum part size for multipart/form-data requests is 10MB
    1633605861811 INFO  API Builder/Wrecsam (4.70.2) uc3/1.0.0
    1633605861811 DEBUG APIKey is: ELQj/5A7pZB8+jrgPm50O9IGF2wqE/tM
    1633605861891 WARN  Your server has no authentication, accessControl.apiPrefixSecurity is unset.
    1633605861894 DEBUG Registering upgrade handler for flow
    1633605861935 INFO  Registered plugin: @axway/api-builder-plugin-fn-base64
    1633605861947 INFO  Registered plugin: @axway/api-builder-plugin-fn-javascript
    1633605861957 INFO  Registered plugin: @axway/api-builder-plugin-fn-json
    1633605861965 INFO  Registered plugin: @axway/api-builder-plugin-fn-logger
    1633605861973 INFO  Registered plugin: @axway/api-builder-plugin-fn-mustache
    1633605861980 INFO  Registered plugin: @axway/api-builder-plugin-fn-restclient
    1633605862037 DEBUG [@axway/api-builder-plugin-fn-swagger] Loading OpenAPI specs from '/Users/jcabrera/work/clients/Imerys/uc3/apibuilder/swagger'
    1633605862037 DEBUG [@axway/api-builder-plugin-fn-swagger] Found the following OpenAPI specs: ["api"]
    1633605862065 INFO  Registered plugin: @axway/api-builder-plugin-fn-swagger
    1633605862099 INFO  Registered plugin: @axway/api-builder-plugin-invoke-flow
    1633605862101 INFO  Registered plugin: @axway-api-builder-ext/api-builder-plugin-dc-postgres
    1633605862126 INFO  Starting connector/memory@built-in
    1633605862126 INFO  Started connector/memory@built-in
    1633605862126 INFO  Starting connector/postgres@1.0.3
    [prompt>

**Comment by jcabrera-axway** [comment]
I'll try the new version and provide feedback, thanks

**Comment by cwiechmann** [comment]
Has been fixed with version 2.0.0
